#!/usr/bin/env sh
DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
export PATH="$DIR/tools/oss-cad-suite/bin:$PATH"
export YOSYSHQ_ROOT="$DIR/tools/oss-cad-suite"
exec "$DIR/bin/cada1100_alpha.bin" "$@"
